Bim4Everyone/RevitPlugins

RevitOpeningPlacement/Models/Extensions/CeilingAndFloorExtension.cs, RevitOpeningPlacement/Models/Extensions/HostObjectExtension.cs, RevitOpeningPlacement/Models/Extensions/LineExtension.cs, RevitOpeningPlacement/Models/Extensions/XYZExtension.cs, RevitOpeningPlacement/Models/OpeningPlacement/PointFinders/FloorPointFinder.cs
Скорректирован алгоритм получения точки вставки для заданий на отверстия в перекрытиях.
Теперь точка вставки - это точка пересечения срединной плоскости перекрытия и оси элемента ВИС.
Было:
Стало:
=> RevitOpeningPlacement: Корректировка получения точки вставки отверстий в перекрытиях

RevitOpeningPlacement/GetOpeningTasksCmd.cs, RevitOpeningPlacement/Models/Extensions/WallExtension.cs
Изменения:
- **Исправлен баг с точкой вставки в стенах, имеющих соединения с другими стенами**
Было:
Стало:
- **Добавлено автоназначение настроек расстановки отверстий КР в соответствии с выбором навигатора:**
=> RevitOpeningPlacement: Исправление бага с точкой вставки

RevitClashes/Models/ProjectConfigBuilder.cs
Исправлен баг, когда пустой файл конфига десериализуется в null, что ломает плагин
=> RevitClashDetective: Исправление бага с загрузкой пустого конфига

.editorconfig
- Добавлены ссылки на документацию по свойствам .editorconfig
- Экспериментальные незадокументированные свойства выключены
- Для некоторых стилей добавлена строгость 'warning', таких как:
- требование явного указания модификаторов доступа для всех членов, кроме публичных методов интерфейсов
- требование отсутствия неиспользуемых параметров методов
- требование модификатора readonly для полей, которые устанавливаются в конструкторе или имеют значение по умолчанию, и потом не меняются
- требование стиля именования camelCase для локальных переменных и входных параметров методов
- требование стиля именования _camelCase для приватных полей
- требование стиля именования PascalCase для остальных членов
- требование стиля именования IPascalCase для интерфейсов
- Теперь предпочтительны using …
=> Обновлен стиль кода и добавлены ссылки на документацию в .editorconfig

.github/workflows/publish.RevitFinishingWalls.yml
Т.к. плагин RevitFinishingWalls использует RevitClashes, добавил триггер на изменение файлов '**RevitClashes**.cs'
=> RevitFinishingWalls: Настроен CI-CD запуска публикации плагина

RevitPlugins.sln, src/RevitClashDetective/ViewModels/Navigator/ReportViewModel.cs, src/RevitClashDetective/ViewModels/Navigator/ReportsViewModel.cs, src/RevitClashDetective/Views/NavigatorView.xaml, src/RevitClashes/Models/GraphicView/ParameterFilterProvider.cs, src/RevitClashes/Models/RevitRepository.cs
Изолирование реализовано через генерацию фильтров по параметрам элементов и последующее отключение видимости элементов.
При нажатой галочке "Изолировать выделенные элементы" элементы изолируются, при отжатой - все фильтры сбрасываются
=> RevitClashDetective: Добавлена возможность изолировать элементы выбранной коллизии

src/RevitReinforcementCoefficient/Models/Analyzers/DesignTypeListAnalyzer.cs, src/RevitReinforcementCoefficient/Models/ElementModels/FormworkElement.cs
Внесены изменения в связи с изменением технологии КР (в очередной раз):
- номер формы семейства-оболочки изменен с 1000 на 10000;
- исправлен подход подсчета объема опалубки (учтен случай, выявленный при тестах, когда опалубочный элемент обладает нулевым объемом).
=> RevitReinforcementCoefficient: Исправления по результатам тестов

src/RevitOpeningPlacement/Models/RevitRepository.cs
Из категорий инженерных элементов ВИС, с которыми работает плагин убрана категория "Воздухораспределители".
Все текущие категории ВИС, с которыми работает плагин:
- Воздуховоды, Соединительные детали воздуховодов, Арматура воздуховодов
- Трубы, Соединительные детали трубопроводов
- Короба, Соединительные телати коробов
- Кабельные лотки, Соединительные детали кабельных лотков
=> RevitOpeningPlacement: Категория "Воздухораспределители" полностью убрана из обработки плагином

src/RevitReinforcementCoefficient/Models/ElementModels/RebarElement.cs
Изменено предельное значение параметра "обр_ФОП_Форма_номер" для арматуры с 200 на 2000
=> RevitReinforcementCoefficient: Исправлено граничное значение параметра для арматуры

src/RevitOpeningPlacement/Models/Configs/MepCategory.cs, src/RevitOpeningPlacement/Models/Configs/MepCategoryCollection.cs, src/RevitOpeningPlacement/ViewModels/OpeningConfig/MainViewModel.cs, src/RevitOpeningPlacement/ViewModels/OpeningConfig/MepCategoryViewModel.cs
Скорректирована инициализация значений по умолчанию, если файл конфига для настроек расстановки заданий на отврестия от ВИС отсутствует. Раньше инициализация настроек по умолчанию происходила только в MainViewModel и нужно было при отсутствии конфига всегда открывать это окно настроек расстановки ВИС и сохранять их.
Сами значения настроек по умолчанию никак не изменились.
=> RevitOpeningPlacement: Скорректировано создание настроек расстановки заданий от ВИС по умолчанию

src/RevitFinishingWalls/Models/PluginConfig.cs, src/RevitFinishingWalls/Models/RevitRepository.cs, src/RevitFinishingWalls/RevitFinishingWallsCommand.cs, src/RevitFinishingWalls/Services/Creation/IRoomFinisher.cs, src/RevitFinishingWalls/Services/Creation/IWallCreationDataProvider.cs, src/RevitFinishingWalls/Services/Creation/Implements/RoomFinisher.cs, src/RevitFinishingWalls/Services/Creation/Implements/WallCreationDataProvider.cs, src/RevitFinishingWalls/ViewModels/MainViewModel.cs, src/RevitFinishingWalls/Views/MainWindow.xaml
- Для отделочных стен теперь можно задать смещение в мм внутрь помещения. Допустимые значения смещения внутрь в диапазоне [0 мм; 200 мм].
- Сохранение конфига сделано раздельно по проектам.
- Добавлен прогресс бар обработки помещений.
- Убрана попытка соединения отделочных стен со связями, т.к. это в принципе нельзя сделать в ревите.
- Добавлен сброс настроек видимости для 3D вида до настроек по умолчанию. Измененные настройки влияют на алгоритм поиска элементов, перекрытых линией-разделителем помещений.
- Улучшен алгоритм поиска элементов, перекрытых линией-разделителем помещений.
=> RevitFinishingWalls: Добавлена возможность указывать смещение отделки внутрь помещения

RevitPlugins.sln, src/RevitClashDetective/ViewModels/Navigator/ClashViewModel.cs, src/RevitClashDetective/ViewModels/Navigator/ReportViewModel.cs, src/RevitClashDetective/Views/NavigatorView.xaml, src/RevitClashes/Models/Clashes/ClashData.cs, src/RevitClashes/Models/Clashes/ClashModel.cs, src/RevitClashes/Models/Clashes/ElementModel.cs, src/RevitClashes/Models/Clashes/TransformModel.cs, src/RevitClashes/Models/RevitRepository.cs
В GUI просмотра коллизий добавлены столбцы:
- % пересечения относительно меньшего элемента
- объем пересечения в м³
=> RevitClashDetective: В навигатор коллизий добавлен вывод % пересечения и объема коллизии

src/RevitRoomTagPlacement/Models/RevitRepository.cs, src/RevitRoomTagPlacement/Models/RoomFromRevit.cs
Исправлена ошибка размещения марок на помещениях из связанных файлов.
Когда скрипт запускается на виде, на котором есть помещения из связанного файла, марки этих помещений размещаются не на самих помещениях, а со смещением.
Для решения проблемы добавлена трансформация координаты марки.
=> RevitRoomTagPlacement: Исправление ошибки со связями

src/RevitServerFolders/Models/RevitRepository.cs
До этого файл rvt открывался с отсоединением без сохранения рабочих наборов, из-за чего на виде Navisworks полностью слетали настройки скрытия рабочих наборов. Теперь файл rvt открывается с отсоединением, с сохранением рабочих наборов, с открытием всех рабочих наборов.
Плашка "Рабочие наборы" есть только в файлах, в которых включена совместная работа соответственно включены рабочие наборы:
=> RevitServerFolders: Исправлена проблема с отсутствием скрытия РН при экспорте в NWC

src/RevitServerFolders/Models/PluginConfig.cs, src/RevitServerFolders/Services/IModelsExportService.cs, src/RevitServerFolders/Services/NwcExportService.cs, src/RevitServerFolders/Services/RvtExportService.cs, src/RevitServerFolders/ViewModels/FileSystemViewModel.cs, src/RevitServerFolders/ViewModels/MainViewModel.cs, src/RevitServerFolders/ViewModels/RsViewModel.cs, src/RevitServerFolders/Views/MainWindow.xaml
Добавлена галочка в выгрузку rvt из RS и nwc из rvt, чтобы можно было включить/отключить очистку целевой папки
=> RevitServerFolders: Добавлена возможность отключать очистку целевой папки

src/RevitServerFolders/Services/NwcExportService.cs
Из-за недостаточных сообщений логов не было понятно, почему не выполняется экспорт RVT в NWC.
Добавлены сообщения, когда не найден вид для экспорта и когда на этом виде не обнаружено элементов для экспорта.
Также сделан выход из обработчика ошибок, когда ошибок не обнаружено.
=> RevitServerFolders: Корректировка сообщений логов

src/RevitServerFolders/Services/NwcExportService.cs
Когда на 3D виде Navisworks выключена видимость всех элементов через GUI, на виде всё еще присутствует 1 элемент - ExtentElem. Из-за этого элемента не работала проверка на Any в списке элементов на виде.
Теперь в Any проверяется также на наличие категории у элементов.
Диалоговое окно модуля по экспорту в NWC, которое возникает, если на вход дать 3D вид с одним ExtentElem, и которое не обрабатывается обработчиком UIApplicationOnDialogBoxShowing:
Значения свойств ExtentElem:
=> RevitServerFolders: Исправление ошибки с поиском элементов на виде

src/RevitClashDetective/Views/ClashReportDiffView.xaml, src/RevitClashDetective/Views/FilterCreatorView.xaml, src/RevitClashDetective/Views/MainWindow.xaml, src/RevitClashDetective/Views/NavigatorView.xaml, src/RevitClashDetective/Views/ProviderComboBox.xaml, src/RevitClashDetective/Views/RevitReportClashNavigator.xaml
При скролле GridControl, в View которого в строках есть ComboBoxEdit, в этих ComboBoxEdit стиралось выбранное значение при скролле.
До скролла:
после скролла:
Надо устанавливать в ComboBoxEdit свойство `AllowUpdateTwoWayBoundPropertiesOnSynchronization="False"`
Ссылка на аналогичную ошибку:
https://supportcenter.devexpress.com/Ticket/Details/T585438/custom-comboboxedit-in-gridcontrol-loses-value-after-scrolling
=> RevitClashDetective: Устранён бага с потерей значений при скролле окна

src/RevitOpeningPlacement/ViewModels/OpeningConfig/MepCategoryViewModel.cs, src/RevitOpeningPlacement/ViewModels/OpeningConfig/SizeViewModel.cs, src/RevitOpeningPlacement/Views/SettingView.xaml
Теперь в GUI параметр "Диаметр" для труб отображается как "Внешний диаметр"
=> RevitOpeningPlacement: Скорректировано отображение названия параметра для диаметра труб в GUI

src/RevitMechanicalSpecification/Models/Fillers/ElementParamSystemFiller.cs, src/RevitMechanicalSpecification/Service/ParamChecker.cs
У некоторых организаций начались сбои, параметр ADSK_Имя системы у них периодически уведен в ReadOnly. 
Убираю его обработку в случае подобной блокировки. 
Заодно возвращаю нормальную настройку параметров - текущая версия шаблона платформы уже устраивает, нет нужды его избегать. 
=> Обновление имени системы: Блокированный параметр

src/RevitBatchPrint/Models/Format.cs, src/RevitBatchPrint/Models/RevitPrint.cs, src/RevitBatchPrint/Models/RevitRepository.cs
- исправил выбор формата при печати
> При разборе ошибки, стало понятно, что это из-за того что в ревите печать стала асинхронной, причиной этого что является не совсем ясно, тут может быть виноват revit, windows, pdf24. При асинхронной печати происходит отправка на печать и возврат управления в код, а код в этот момент удаляет формат листа, а pdf24 при печати потом выбирает случайный.
решение:
удаление формата происходит при запуске печати.
создаем во время печати нужный формат, а потом в конце его не удаляем.
=> Пакетная печать: Исправление выбора формата при печати

src/RevitMechanicalSpecification/Models/RevitRepository.cs, src/RevitMechanicalSpecification/RevitMechanicalCreateNameCmd.cs, src/RevitMechanicalSpecification/RevitMechanicalFullRefreshCmd.cs, src/RevitMechanicalSpecification/RevitMechanicalFunctionRefreshCmd.cs, src/RevitMechanicalSpecification/RevitMechanicalSelectedFullRefreshCmd.cs, src/RevitMechanicalSpecification/RevitMechanicalSpecificationRefreshCmd.cs, src/RevitMechanicalSpecification/RevitMechanicalSystemRefreshCmd.cs, src/RevitMechanicalSpecification/RevitMechanicalVisibleFullRefreshCmd.cs, src/RevitMechanicalSpecification/Service/CollectionFactory.cs, src/RevitMechanicalSpecification/Service/VisElementsCalculator.cs
Для работы в больших командах стало критичным взаимозанимание элементов при настройке спеки. 
Воизбежание:
Добавляем возможжность обновить полностью только выделенные элементы
Добавляем возможность обновить полностью только видимые элементы
Багфикс:
Поправил условие для деления размера фитингов воздуховодов, работало некорректно
=> Полное обновление: Преобразование в выпадающий список

src/RevitOpeningPlacement/Views/NavigatorArIncomingView.xaml, src/RevitOpeningPlacement/Views/NavigatorMepIncomingView.xaml
=> RevitOpeningPlacement: Исправлено правописание в навигаторе АР-КР

src/RevitServerFolders/Services/NwcExportService.cs
Предыдущая логика проверки только на наличие категории у элементов работает не во всех случаях. Теперь проверяется наличие на виде "Navisworks" элементов с категорией и солидами с ненулевым объемом.
=> RevitServerFolders: Скорректирована проверка на наличие элементов для экспорта

src/RevitMechanicalSpecification/Entities/VisSystem.cs, src/RevitMechanicalSpecification/Models/Fillers/ElementParamFunctionFiller.cs, src/RevitMechanicalSpecification/Models/Fillers/ElementParamSystemFiller.cs, src/RevitMechanicalSpecification/Models/RevitRepository.cs, src/RevitMechanicalSpecification/Models/SpecConfiguration.cs, src/RevitMechanicalSpecification/Service/CollectionFactory.cs, src/RevitMechanicalSpecification/Service/ElementProcessor.cs, src/RevitMechanicalSpecification/Service/MaskReplacer.cs, src/RevitMechanicalSpecification/Service/ParamChecker.cs, src/RevitMechanicalSpecification/Service/SystemFunctionNameFactory.cs
В качестве теста добавляем обработку параметра денежной единицы вместо числового. 
Правка бага: из-за некорректного вызова обновления маски элементы обрабатывались со второго раза. Теперь вызываем перед основным процессом заполнения спецификации, передавая список элементов, характерный для конкретной команды. Позволяет во время обработки спецификации выдерживать единую логику и работать с полностью заполненными элементами
Правка бага: если разместить генерик-семейство с маской, а потом маску вычистить - связанный параметр не вычищался
Замена параметра: устаревший параметр ФОП_ВИС_Экономическая функция приведен к стандартному имени (ФОП_ВИС_ЭФ принудительная) и повторяет логику работы ФОП_ВИС_Имя системы принудительная
=> Вкладка спецификаций: Поэкземплярная работа групп

.github/templates/RevitPluginTemplate/Models/PluginConfig.cs, .github/templates/RevitPluginTemplate/Models/RevitRepository.cs, .github/templates/RevitPluginTemplate/RevitPluginTemplateCommand.cs, .github/templates/RevitPluginTemplate/ViewModels/MainViewModel.cs, .github/templates/RevitPluginTemplate/Views/MainWindow.xaml, .github/templates/RevitPluginTemplate/Views/MainWindow.xaml.cs, src/RevitPlugins/Models/PluginConfig.cs, src/RevitPlugins/Models/RevitRepository.cs, src/RevitPlugins/RevitPluginsCommand.cs, src/RevitPlugins/ViewModels/MainViewModel.cs, src/RevitPlugins/Views/MainWindow.xaml, src/RevitPlugins/Views/MainWindow.xaml.cs
- кодировка файлов по editorconfig
- табы заменены на пробелы
- убраны лишние пустые строки
- убраны лишние пробелы
- скорректировано расположение фигурных скобок
- скорректированы отступы строк в *.xaml
- скорректированы отступы строк в *.cs
=> RevitPluginTemplate: Скорректирован стиль шаблонов плагинов

src/RevitScheduleImport/Services/LengthConverter.cs, src/RevitScheduleImport/Services/ScheduleImporter.cs, src/RevitScheduleImport/Views/MainWindow.xaml
- Теперь высота текста в Revit и в Excel на печати имеет одинаковую высоту
- Исправлен баг с необновлямой высотой текста на спеках, расположенных на листах. Надо вызывать `Document.Regenerate`
- Кнопка "ОК" в GUI автоматом нажимается на Enter
=> RevitScheduleImport: Исправлена высота текста

src/RevitOpeningPlacement/Models/OpeningPlacement/PointFinders/FloorOpeningsGroupPointFinder.cs
=> RevitOpeningPlacement: Скорректирована точка вставки объединенных отверстий в перекрытиях

src/RevitServerFolders/Services/NwcExportService.cs
`GetSolids` сейчас падает, когда `get_Geometry` возвращает `null`, из-за чего экспорт файла прерывался. Добавил перехват исключений.
=> RevitServerFolders: Исправлен алгоритм проверки на наличие геометрии у элемента

src/RevitOpeningPlacement/Services/MepTaskOutcomingInfoUpdater.cs
Исправлено ложное назначение статуса "Ошибка геометрии", когда возникало исключение в результате фильтрации по пустой коллекции.
=> RevitOpeningPlacement: Исправление ошибки с определением статуса "Ошибка геометрии"

src/RevitOpeningPlacement/Models/Configs/MepConfigPath.cs, src/RevitOpeningPlacement/Models/Configs/OpeningConfig.cs, src/RevitOpeningPlacement/Services/ConfigFileService.cs, src/RevitOpeningPlacement/SetOpeningTasksPlacementConfigCmd.cs, src/RevitOpeningPlacement/ViewModels/OpeningConfig/MainViewModel.cs, src/RevitOpeningPlacement/ViewModels/Services/ConfigLoaderService.cs, src/RevitOpeningPlacement/ViewModels/Services/ConfigSaverService.cs, src/RevitOpeningPlacement/Views/MainWindow.xaml
Настройки расстановки отверстий ВИС теперь при выполнении команды "Сохранить как" сохраняются по заданному пути и становятся редактируемыми в окне. При "Загрузке" настроек из файла также станосится редактируемым этот загруженный файл.
Чтобы посмотреть путь к редактируемому файлу добавлена кнопка в GUI, открывающая окно проводника в папке конфига с выделением редактируемого файла:
=> RevitOpeningPlacement: Добавлена возможность редактировать настройки ВИС из заданного файла

src/RevitClashes/Models/RevitParamConverter.cs
Кодировка файла исправлена в соответствии с `.editorconfig`
=> RevitClashDetective: Исправлениа кодировка в RevitParamConverter.cs

src/RevitMechanicalSpecification/Service/VisElementsCalculator.cs
Ранее не был продуман момент перехода с трубы на которой считаются фитинги на трубу на которой не считаются. Теперь в этих случаях фитинг учитывается всегда.
=> RevitMechanicalSpecification: Правка поиска наименований фитингов труб

.editorconfig
В раздел Naming styles добавлен модификатор protected для полей.
Поля, которые имеют только модификатор protected должны иметь camelCase и префикс "_".
=> Обновление editorconfig

src/RevitServerFolders/NavisworksExportCommand.cs
Команда по экспорту в NWC из RVT не работает, если не установлен плагин Navisworks NWC Export Utility. Добавлена проверка на установку этого плагина.
=> RevitServerFolders: Добавлена проверка установки плагина Navisworks NWC Export Utility

src/RevitClashDetective/ViewModels/FilterCreatorViewModels/CategoriesInfoViewModel.cs, src/RevitClashes/Models/FilterGenerators/RevitFilterGenerator.cs
- Исключена возможность выбирать параметр для фильтрации при редактировании поискового набора, когда этот параметр отсутствует в активном документе. Ранее было возможно выбрать параметр, который есть в какой-то связи и сохранить изменения. При загрузке конфига происходила ошибка десериализации, т.к. параметра в активном документе нет.
- Исправлена ошибка `ArgumentNullException`, которая возникала при создании `FilterInverseRule` с `null` параметром конструктора.
=> RevitClashDetective: Отключен выбор параметра фильтра, которого нет в активном документе

src/RevitOpeningPlacement/ViewModels/OpeningConfig/CategoriesInfoViewModel.cs
Исключена возможность выбирать параметр для фильтрации при редактировании фильтра, когда этот параметр отсутствует в активном документе. Ранее было возможно выбрать параметр, который есть в какой-то связи и сохранить изменения. При загрузке конфига происходила ошибка десериализации и генерился конфиг по умолчанию, т.к. параметра в активном документе нет.
=> RevitOpeningPlacement: Отключен выбор параметра фильтра, которого нет в активном документе

src/RevitMechanicalSpecification/Models/Fillers/ElementParamGroupFiller.cs
Пропущено ключевое слово "_Узел_" в формировании содержимого группирования, по которому нумерация фильтровалась. Инженеров не смущало влоть до нормоконтроля от ГИП.
=> RevitMechanicalSpecification: Сортировка узлов

src/RevitDeclarations/Models/Export/DeclarationData/CommercialDataTable.cs, src/RevitDeclarations/Models/Export/Exporters/ExcelExporter.cs, src/RevitDeclarations/Models/Rooms/CommercialRooms.cs
Исправлены ошибки:
- конвертации числа в дату в Excel
- отсутствия параметра класса машино-места в итоговой таблице
=> RevitDeclarations: Исправлена ошибка конвертации дат и вывода класса ММ

.nuke/build.schema.json, build/Build.Compile.cs, build/_build.csproj
- обновил зависимости nuke
- изменил логику публикации плагинов
- `nuke compile` - компиляция в папку `bin`
- `nuke publish` - компиляция в папку плагина в платформу (на вкладку)
- локальная сборка - конфигурация выбирается `Debug`, 
- сборка на сервере - конфигурация выбирается `Release` 
было:
- конфигурация
- `nuke compile` - Debug
- `nuke publish` - Release
- output
- `nuke compile` - компиляция в папку плагина в платформу (на вкладку)
- `nuke publish` - компиляция в папку плагина в платформу (на вкладку)
=> Nuke: Обновлены зависимости

src/RevitMechanicalSpecification/Models/Fillers/ElementParamNumberFiller.cs
Исправлена ошибка, на изоляции фитингов воздуховодов принимался запас воздуховодов, а не изоляции
=> RevitMechanicalSpecification: Исправлена ошибка с подсчетом изоляции фитингов

src/RevitDeclarations/Models/RoomParamProvider.cs, src/RevitDeclarations/Models/Rooms/Apartment.cs, src/RevitDeclarations/Models/Rooms/CommercialRooms.cs, src/RevitDeclarations/Models/Rooms/RoomGroup.cs, src/RevitDeclarations/Views/TabItems/ParamsCommercialTabItem.xaml
1. Изменена точность округления высот помещений 
2. Исправлены мелкие замечания по форматированию текста
3. Исправлена опечатка в GUI
=> RevitDeclarations: Скорректированы значения параметров декларации

src/RevitOpeningPlacement/Models/RealOpeningArPlacement/RealOpeningArPlacer.cs, src/RevitOpeningPlacement/Models/RealOpeningKrPlacement/RealOpeningKrPlacer.cs, src/RevitOpeningPlacement/OpeningModels/OpeningRealBase.cs
Семейства отверстий АР и КР - это полые семейства вырезания. У них нет твердотельной геометрии, поэтому обычное использование `GetSolid` ничего не даст.
Брался экземпляр семейства отверстия (АР/КР), бралась его основа. Производилась попытка построить исходную геометрию (solid) основы до вырезания отверстия в ней. Из исходной геометрии основы вырезалась текущая геометрия (solid) основы. По разнице солидов получались солиды отверстий. Из этих солидов, если их получилось несколько, выбирался ближайший.
Плюсы:
- алгоритм не зависит от формы/названия/параметров элементов
Минусы:
- сложно определять исходную геометрию основы. Особенно это касается случаев, когда отверстие примыкает к торцу основы, что сейчас вообще работает неправильно
- алгоритм долго работает
- можно неправильно определить …
=> RevitOpeningPlacement: Обновлен алгоритм определения солида отверстий АР и КР

src/RevitOpeningPlacement/Models/Interfaces/IOpeningTaskHost.cs, src/RevitOpeningPlacement/Models/Interfaces/IOpeningTaskIncomingForKrViewModel.cs, src/RevitOpeningPlacement/OpeningModels/OpeningArTaskIncoming.cs, src/RevitOpeningPlacement/OpeningModels/OpeningTaskHost.cs, src/RevitOpeningPlacement/ViewModels/Navigator/ConstructureNavigatorForIncomingTasksViewModel.cs, src/RevitOpeningPlacement/ViewModels/Navigator/OpeningArTaskIncomingViewModel.cs, src/RevitOpeningPlacement/ViewModels/Navigator/OpeningMepTaskIncomingViewModel.cs, src/RevitOpeningPlacement/Views/NavigatorArIncomingView.xaml
В окно навигатора по заданиями для КР для входящих заданий добавлены столбцы:
- Основа (Название типоразмера элемента из активного файла, в котором размещено задание на отверстие из связи)
- Id основы (с дополнительной кнопкой для выбора основы)
- Раздел КР (Значение параметра экземпляра основы "**обр_ФОП_Раздел проекта**")
=> RevitOpeningPlacement: Добавлены столбцы в окно навигатора КР для входящих заданий

src/RevitOpeningPlacement/Views/NavigatorMepIncomingView.xaml
В предыдущем #149 свойство `IOpeningTaskIncomingForKrViewModel.HostName` переехало в `IOpeningTaskIncomingForKrViewModel.Host.Name`, что также затронуло окно навигатора АР.
=> RevitOpeningPlacement: Исправлено отображение названия основы задания в навигаторе АР

.nuke/build.schema.json
Сейчас каждый раз при сборке нюком в схему добавляется сгенерированное свойство `PluginType`
=> Nuke: В схему сборки добавлен PluginType

src/RevitOpeningPlacement/Models/OpeningPlacement/ParameterGetters/ParametersGetters/FloorSolidParameterGetter.cs, src/RevitOpeningPlacement/Models/OpeningPlacement/ParameterGetters/ParametersGetters/InclinedRectangleCurveWallParameterGetter.cs, src/RevitOpeningPlacement/Models/OpeningPlacement/ParameterGetters/ParametersGetters/InclinedRoundCurveWallParamGetter.cs, src/RevitOpeningPlacement/Models/OpeningPlacement/ParameterGetters/ParametersGetters/PerpendicularRectangleCurveFloorParamGetter.cs, src/RevitOpeningPlacement/Models/OpeningPlacement/ParameterGetters/ParametersGetters/PerpendicularRectangleCurveWallParamGetter.cs, src/RevitOpeningPlacement/Models/OpeningPlacement/ParameterGetters/ParametersGetters/PerpendicularRoundCurveFloorParamGetter.cs, src/RevitOpeningPlacement/Models/OpeningPlacement/ParameterGetters/ParametersGetters/PerpendicularRoundCurveWallParamGetter.cs, src/RevitOpeningPlacement/Models/OpeningPlacement/ParameterGetters/ParametersGetters/WallSolidParameterGetter.cs, src/RevitOpeningPlacement/Models/OpeningPlacement/ValueGetters/BottomOffsetOfOpeningInFloorValueGetter.cs, src/RevitOpeningPlacement/Models/OpeningPlacement/ValueGetters/BottomOffsetOfRectangleOpeningInWallValueGetter.cs, src/RevitOpeningPlacement/Models/OpeningPlacement/ValueGetters/BottomOffsetValueGetter.cs, src/RevitOpeningPlacement/Models/OpeningPlacement/ValueGetters/CenterOffsetOfRectangleOpeningInWallValueGetter.cs, src/RevitOpeningPlacement/Models/OpeningPlacement/ValueGetters/CenterOffsetValueGetter.cs, src/RevitOpeningPlacement/Models/OpeningPlacement/ValueGetters/ElevationValueGetter.cs, src/RevitOpeningPlacement/Models/OpeningPlacement/ValueGetters/OffsetFromLevelValueGetter.cs, src/RevitOpeningPlacement/Models/OpeningPlacement/ValueGetters/OffsetInFeetValueGetter.cs, src/RevitOpeningPlacement/Models/OpeningPlacement/ValueGetters/OffsetInMmValueGetter.cs
Определение высотных отметок заданий на отверстия от ВИС сделано от базовой точки проекта, а не от внутреннего начала проекта, как было ранее.
=> RevitOpeningPlacement: Исправлено определение высотных отметок у заданий от ВИС

src/RevitOpeningPlacement/Models/OpeningPlacement/OpeningPlacer.cs
При выполнении команды "Расставить все" выскакивала следующая ошибка:
При отладке выяснилось, что данная ошибка возникает при определении точки вставки задания на отверстие и должна далее попадать в соответствующее окно с ошибками расстановки заданий.
Скорректированы перехватываемые исключения при определении точки вставки
=> RevitOpeningPlacement: Исправлена ошибка определения точки вставки, прерывающая выполнение команды

src/RevitDeclarations/Models/DeclarationProjects/ApartmentsProject.cs, src/RevitDeclarations/Models/Priorities/RoomPriority.cs, src/RevitDeclarations/Models/RevitRepository.cs, src/RevitDeclarations/Models/RoomConnectionAnalyzer.cs, src/RevitDeclarations/Models/Rooms/RoomElement.cs, src/RevitDeclarations/Models/Rooms/Separators/CurveRoomSeparator.cs, src/RevitDeclarations/Models/Rooms/Separators/FamInstanceRoomSeparator.cs, src/RevitDeclarations/Models/Rooms/Separators/RoomSeparator.cs, src/RevitDeclarations/Models/UtpCalculator.cs, src/RevitDeclarations/ViewModels/MainViewModels/ApartmentsMainVM.cs, src/RevitDeclarations/ViewModels/MainViewModels/CommercialMainVM.cs, src/RevitDeclarations/ViewModels/MainViewModels/PublicAreasMainVM.cs
Для квартир при расчете УТП "Мастер-спальня" должно учитываться соединение спален и СУ.
В предыдущей версии учитывалось соединение помещений только через двери.
Теперь скрипт учитывает соединение помещений через линии разделителей помещений.
=> RevitDeclarations: Обновлены правила расчета УТП "Мастер-спальня"

src/RevitDeclarations/Models/RevitRepository.cs
Если в Revit у экземпляра семейства совпадает стадии сноса и возведения, то элемент имеет временный статус.
Для таких экземпляров в Revit API нельзя получить связанные помещения.
При наличии таких экземпляров при расчете УТП возникала ошибка (для дверей и сантехники).
Теперь этот статус удален из списка статусов для фильтрации элементов.
=> RevitDeclarations: Исправлена ошибка "временных" семейств

src/RevitMechanicalSpecification/Models/Fillers/ElementParamNameFiller.cs
Лишний пробел по умолчанию в именах ломал сортировку узлов в сложных спецификациях
=> RevitMechanicalSpecification: Лишний пробел в наименовании

src/RevitReinforcementCoefficient/Models/Analyzers/DesignTypeListAnalyzer.cs, src/RevitReinforcementCoefficient/Models/ElementModels/RebarElement.cs
Решены проблемы:
- не учтены некоторые диаметры арматурных стержней для расчета;
- данные, которые в Revit в параметре записаны целым числом иногда могут приходить с дробной частью после конвертации из внутренних единиц; 
- решена проблема двойственности параметра "обр_ФОП_Орг. уровень" в семействах (и различия их типов данных; в результате несогласованных действий разработчиков семейств, некоторые семейства могут содержать два параметра с именем "обр_ФОП_Орг. уровень" разных типов данных).
=> RevitReinforcementCoefficient: Изменен расчет арматуры

src/RevitApartmentPlans/Models/Apartment.cs, src/RevitApartmentPlans/Models/PluginConfig.cs, src/RevitApartmentPlans/Models/RevitRepository.cs, src/RevitApartmentPlans/Models/RoomElement.cs, src/RevitApartmentPlans/RevitApartmentPlansCommand.cs, src/RevitApartmentPlans/Services/BoundsCalculationService.cs, src/RevitApartmentPlans/Services/IViewPlanCreationService.cs, src/RevitApartmentPlans/Services/LinkFilterProvider.cs, src/RevitApartmentPlans/Services/ViewPlanCreationService.cs, src/RevitApartmentPlans/ViewModels/ApartmentsViewModel.cs, src/RevitApartmentPlans/ViewModels/MainViewModel.cs, src/RevitApartmentPlans/Views/MainWindow.xaml
- Добавлена обработка помещений из связанных файлов. В 2022 и 2023 может работать некорректно из-за отсутствующего функционала в api revit:
- [перегрузка](https://www.revitapidocs.com/2024/968b52a0-de55-2f96-de40-968812bc41c7.htm) конструктора `FilteredElementCollector` для фильтрации элементов из связи, видимых на виде активного документа, которая появилась только в 2024 версии
- [выделение](https://www.revitapidocs.com/2023/813a9d31-bc4f-1ebc-9a7b-69a2a99d22ac.htm) элементов из связей через `Reference`, которое появилось только в 2023 версии
- Добавлена возможность копировать элементы детализации с активного вида
При включении обработки связей в 2022 и 2023 версии появляется кнопка для отображения предупреждения:
=> RevitApartmentPlans: Добавлена обработка связей и копирование детализации

src/RevitMechanicalSpecification/Models/Fillers/ElementParamUnitFiller.cs
Правка филлера единиц измерения - ранее игнорировались размерности комплектов, заменяясь штуками.
=> RevitMechanicalSpecification: Единицы измерения

src/RevitOpeningPlacement/Models/OpeningPlacement/AngleFinders/FloorOpeningsGroupAngleFinder.cs, src/RevitOpeningPlacement/Models/OpeningPlacement/AngleFinders/WallOpeningsGroupAngleFinder.cs, src/RevitOpeningPlacement/Models/OpeningPlacement/PointFinders/FloorOpeningsGroupPointFinder.cs, src/RevitOpeningPlacement/Models/OpeningPlacement/PointFinders/WallOpeningsGroupPointFinder.cs, src/RevitOpeningPlacement/Models/OpeningPlacement/SolidProviders/OpeningGroupSolidProvider.cs, src/RevitOpeningPlacement/Models/OpeningUnion/OpeningsGroup.cs, src/RevitOpeningPlacement/OpeningModels/OpeningMepTaskOutcoming.cs
Новый алгоритм лучше определяет наличие касающихся заданий на отверстия.
Например, если одно задание касается  изнутри другого, но имеет другую форму, то это определяется как касание.
<div style="align-items: left;">
</div>
Если задания на отверстия касаются снаружи, но они смещены друг относительно друга, то это тоже теперь определяется как касание
<div style="align-items: left;">
</div>
=> RevitOpeningPlacement: Обновлен алгоритм проверки касающихся заданий на отверстия

src/RevitRoomTagPlacement/Models/Apartment.cs, src/RevitRoomTagPlacement/Models/RevitRepository.cs
Исправлена ошибка маркировки помещений с максимальной площадью и помещений по имени для связанных файлов.
Так как для связанных файлов нельзя получить помещения с активного вида, то скрипт получает все помещения из связи. В дальнейшем скрипт удаляет марки тех помещений, которые не видны на текущем виде.
Ошибка заключалась в том, что помещение с максимальной площадью (или помещение по заданному имени) находилось одно для всех уровней группы и это могло быть помещения не с активного уровня. Теперь помещение находится для каждого уровня.
=> RevitRoomTagPlacement: Исправлена ошибка маркировки связей

src/RevitRoomExtrusion/Models/RoomChecker.cs
Упростил метод, так как плагин валится на половине помещений.
=> ReviRoomExtrusion : Исправлен метод проверки контуров помещений

src/RevitAxonometryViews/RevitAxonometryViewsCommand.cs
Убрал биндинг uiApp, т.к. он в итоге приводил к крашу плагина при включенной телеметрии
=> RevitAxonometryViews: Исправление ошибки телеметрии

src/RevitCreatingFiltersByValues/Models/ExportContext.cs, src/RevitCreatingFiltersByValues/Models/FilterElemsByExportService.cs, src/RevitCreatingFiltersByValues/Models/RevitRepository.cs
Плагин применяется для создания фильтров (переопределения графики на виде иным способом) по значениям элементов, видимых на виде.
В связи с тем, что появилась потребность создавать фильтры по значениям элементов из связанных файлов, была изменена методика получения элементов (предыдущая не работала корректна с элементами из связей). Получение элементов теперь производится при помощи экспорта.
Изменения интерфейса плагина отсутствуют.
=> RevitCreatingFiltersByValues: Изменен способ получения элементов

src/RevitClashDetective/ViewModels/Navigator/ClashViewModel.cs, src/RevitClashDetective/Views/NavigatorView.xaml, src/RevitClashDetective/Views/RevitReportClashNavigator.xaml, src/RevitClashes/Models/ClashDetection/ClashDetector.cs, src/RevitClashes/Models/Clashes/ClashModel.cs, src/RevitClashes/Models/Clashes/ElementModel.cs, src/RevitClashes/Models/RevitClashReport/NavisXmlClashesLoader.cs, src/RevitClashes/Models/RevitRepository.cs
- в интерфейс навигатора добавлены столбцы с названием коллизии и именем семейства. Столбец с названием коллизии сделан редактируемым
- добавлен импорт статусов из xml отчета Navisworks
- в окне навигатора теперь отображаются коллизии, где хотя бы один из элементов коллизии находится в одном из подгруженных связанных файлов или в активном документе
=> RevitClashDetective: Обновлен навигатор по коллизиям

src/RevitClashes/Models/Extensions/ElementExtensions.cs
Свойство [`Solid.Volume`](https://www.revitapidocs.com/2022/4b4088b8-2096-e7f8-d72f-fc1402592967.htm) может выбрасывать `InvalidOperationException`, добавлен метод для перехватывания этого исключения.
=> RevitClashDetective: Исправлена ошибка получения объема солидов

src/RevitClashes/Models/RevitClashReport/NavisXmlClashesLoader.cs
Название проекта Revit, которое приходит для валидации из xml, содержит расширение в конце (rvt). Старая логика валидации не учитывала, что надо отбрасывать этот суффикс. На тестовом файле это не было видно, потому что у него был дополнительный суффикс "_отсоединено", который отбрасывается в методе `GetDocumentName`.
Так как метод по валидации названия проекта из xml не играет никакой роли (элементы каждой коллизии потом снова проверяются на существование в активном документе или в какой-нибудь связи), принято решение его полностью удалить.
=> Коллизии: Убрана лишняя проверка названия импортируемого проекта

src/RevitClashDetective/ViewModels/Navigator/ReportsViewModel.cs, src/RevitClashes/Models/Clashes/ClashesConfig.cs, src/RevitClashes/Models/ProjectConfigBuilder.cs, src/RevitClashes/Models/RevitRepository.cs
Из-за невозможности совместной работы в файле отчета о коллизиях на общем диске, все файлы отчетов о коллизиях сохраняются теперь всегда в документы пользователя. Таки мобразом каждый пользователь будет всегда работать только со своей версией отчета.
=> RevitClashDetective: Сохранение файлов отчетов перенесено в документы пользователя

src/RevitDeclarations/Models/Export/DeclarationData/DeclarationDataTable.cs, src/RevitDeclarations/Models/RevitRepository.cs, src/RevitDeclarations/Models/Rooms/Apartment.cs, src/RevitDeclarations/Models/Rooms/RoomElement.cs, src/RevitDeclarations/ViewModels/ParametersViewModels/ApartmentsParamsVM.cs, src/RevitDeclarations/ViewModels/ParametersViewModels/ParametersViewModel.cs, src/RevitDeclarations/Views/TabItems/ParamsApartmentsTabItem.xaml
В плагине RevitRooms для параметра количества комнат изменен тип данных на "Денежная единица".
Соответственно для этого плагина должны теперь выводиться параметры и типа "Целое", и типа "Денежная единица".
Для этих изменений исправлен код:
- Добавлен метод получения параметров по ForgeTypeId 
- Изменен тип данных с int на double для свойства RoomsAmount 
- При получении значения параметра добавлена проверка на StorageType
=> RevitDeclarations: Обновлен список выводимых параметров для количества комнат 

src/RevitReinforcementCoefficient/Models/Analyzers/DesignTypeListAnalyzer.cs
С целью обеспечения корректного расчета была добавлена фильтрация опалубки по параметру марки бетона B. 
В соответствии с ТЗ, если у опалубочных элементов параметр "обр_ФОП_Марка бетона B" имеет значение равное "0", то значит данный элемент не армируется, а значит не подходит для расчета коэффициента армирования.
=> RevitReinforcementCoefficient: Добавлена фильтрация опалубки

.nuke/build.schema.json, src/RevitMechanicalSpecification/Models/Fillers/ElementParamGroupFiller.cs
Модификация группирования для работы с узлами с одинаковым именем но различным содержимым. Сортировка должна идти по имени типоразмера узлов.
=> RevitMechanicalSpecification: Правка группирований

src/RevitBatchPrint/BatchPrintCommand.cs, src/RevitBatchPrint/Models/RevitRepository.cs, src/RevitBatchPrint/ViewModels/AlbumViewModel.cs, src/RevitBatchPrint/ViewModels/MainViewModel.cs, src/RevitBatchPrint/ViewModels/SheetViewModel.cs, src/RevitBatchPrint/Views/MainWindow.xaml, src/RevitBatchPrint/Views/MainWindow.xaml.cs, src/RevitBatchPrint/ViewsTemplates/TreeViewTemplate.xaml, src/RevitBatchPrint/assets/localization/Language.en-US.xaml, src/RevitBatchPrint/assets/localization/Language.ru-RU.xaml
- была исправлена ошибка падения ревита, когда у какого-нибудь листа не было основной надписи
- добавил отображение предупреждения, когда выводят на печать листы, у которых есть виды без подрезки
- добавил оптимизацию первого запуска плагина
- изменил режим работы по умолчанию на экспорт в Revit 2022+
=> RevitBatchPrint: Исправить ошибку падения Revit

src/RevitCorrectNamingCheck/Localization/Language.en-US.xaml, src/RevitCorrectNamingCheck/Localization/Language.ru-RU.xaml, src/RevitCorrectNamingCheck/Models/LinkedFile.cs, src/RevitCorrectNamingCheck/Models/LinkedFileEnricher.cs, src/RevitCorrectNamingCheck/Models/RevitRepository.cs, src/RevitCorrectNamingCheck/Views/MainWindow.xaml, src/RevitCorrectNamingCheck/Views/Selectors/WorksetTemplateSelector.cs, src/RevitCorrectNamingCheck/Views/Templates/LinkedFileTemplates.xaml, src/RevitCorrectNamingCheck/Views/Templates/WorksetTemplates.xaml
Внесены следующие изменения:
- Добавлена колонка статуса закрепления связи
- Изменена логика заполнения статуса РН и связанного файла
- Изменены цвета статуса имени РН и связанного файла
=> RevitCorrectNamingCheck: Доработка плагина

src/RevitSleeves/Models/Placing/SleeveModel.cs
- Исправлена ошибка, когда гильзы в многослойных стенах не объединялись после создания
=> RevitSleeves: Исправлена ошибка объединения гильз

src/RevitFinishing/Models/Finishing/FinishingElements/FinishingElement.cs, src/RevitFinishing/Models/Finishing/FinishingType.cs, src/RevitFinishing/Models/KeyFinishingType.cs, src/RevitFinishing/Models/RevitRepository.cs, src/RevitFinishing/Services/FinishingValidationService.cs, src/RevitFinishing/Services/ProjectValidationService.cs, src/RevitFinishing/ViewModels/MainViewModel.cs, src/RevitFinishing/ViewModels/Notices/IWarningItemViewModel.cs, src/RevitFinishing/ViewModels/Notices/Lists/NoticeListViewModel.cs, src/RevitFinishing/ViewModels/Notices/WarningElementViewModel.cs, src/RevitFinishing/ViewModels/Notices/WarningScheduleKeyVM.cs, src/RevitFinishing/Views/ErrorsWindow.xaml, src/RevitFinishing/assets/Localization/Language.en-US.xaml, src/RevitFinishing/assets/Localization/Language.ru-RU.xaml
1. Исправлено свойство по которому выводится уровень помещений для выбора (вместо верхнего предела теперь уровень)
2. Добавлена очистка параметров отделки при каждом запуске
3. Добавлена проверка на используемые стили отделки. В ключевой спецификации у одного ключа могут быть заполнены несколько параметров типов отделки, но не все могут использоваться в проекте. Теперь плагин проверяет количество используемых типов отделки и если оно отличается от ключевой спецификации, то выводится предупреждение.
=> RevitFinishing: Исправлен плагин

src/RevitAxonometryViews/ViewModels/HvacSystemViewModel.cs, src/RevitAxonometryViews/ViewModels/MainViewModel.cs, src/RevitAxonometryViews/Views/MainWindow.xaml
Апдейт для упрощения жизни проектировщиков:
1) Для упрощения работы первичный критерий сортировки заменен на ФОП_ВИС_Имя системы, вместо системного. При детальном рассмотрении оказалось, что системное мы очень редко берем в работу.
2) При этом, дублирующиеся системы с разным ФОП_ВИС_Имя системы должны схлопываться в одну позицию <Варианты>, чтобы избежать ситуаций где человек нащелкивает 50 идентичных чекбоксов из-за непонимания принципа работы.
=> RevitAxonometryViewUpdate: Сортировка по "ФОП_ВИС_Имя системы", сворачивание дубликатов

src/RevitListOfSchedules/Models/SheetElement.cs
Исправлена последовательность построения строки изменений. 
Ранее была ошибка - добавлялось к каждому изменению "Изм.1", теперь только в начале - "Изм". Также убраны пробел и кавычки в конце.
=> RevitListOfSchedues: Исправление ошибки построения строки изменений
