RevitMepTotals/Models/DuctData.cs
RevitMepTotals/Models/Interfaces/IMepData.cs
RevitMepTotals/Models/PipeData.cs
RevitMepTotals/Models/PipeInsulationData.cs
RevitMepTotals/Models/RevitRepository.cs
RevitMepTotals/RevitMepTotalsCommand.cs
RevitMepTotals/Services/Implements/DataExporter.cs
RevitMepTotals/Services/Implements/DocumentsProcessor.cs

Добавлен параметр имя системы в отчет

RevitMepTotals: Добавлен параметр имя системы в отчет

---

RevitMepTotals/Models/DuctData.cs
RevitMepTotals/Models/Interfaces/IDuctData.cs
RevitMepTotals/Models/RevitDocument.cs
RevitMepTotals/Models/RevitRepository.cs
RevitMepTotals/RevitMepTotalsCommand.cs
RevitMepTotals/Services/IConstantsProvider.cs
RevitMepTotals/Services/IErrorMessagesProvider.cs
RevitMepTotals/Services/Implements/ConstantsProvider.cs
RevitMepTotals/Services/Implements/DataExporter.cs
RevitMepTotals/Services/Implements/DocumentsProcessor.cs
RevitMepTotals/Services/Implements/ErrorMessagesProvider.cs
RevitMepTotals/ViewModels/MainViewModel.cs

- Для воздуховодов в список выгружаемых параметров добавлена "Площадь"
- Окно выбора папки для выгрузки теперь открывается перед началом обработки документов

Выгрузить объемы: добавление параметра "Площадь" для выгрузки

---

RevitCopyViews/ViewModels/CopyUserViewModel.cs

Удалил создание шаблона вида для копируемых видов пользователя

RevitCopyViews: Удалил создание шаблона вида для копируемых видов пользователя

---

.github/workflows/publish.RevitPlugins.yml
.nuke/build.schema.json
GitVersion.yml
build/Build.CloneExtensions.cs
build/Build.Compile.cs
build/Build.CreatePullRequest.cs
build/Build.Params.cs
build/Build.PublishArtifacts.cs
build/Build.cs
build/VersioningExtensions.cs
build/_build.csproj

- добавлена автоматическая сборка

Nuke: Тест сборки плагина RevitPlugins

---

.github/workflows/publish.RevitPlugins.yml
build/Build.Params.cs
src/RevitPlugins/RevitPluginsCommand.cs

RevitPlugins: Тестирование автосборки

---

src/RevitClashes/Models/RevitRepository.cs
src/RevitCopyStandarts/CopyStandartsRevitCommand.cs
src/RevitFamilyExplorer/OpenFamilyExplorerCommand.cs
src/RevitFamilyExplorer/RegisterFamilyExplorerCommand.cs
src/RevitLintelPlacement/Models/RevitRepository.cs

Ссылки на диск T заменены на диск W.

RevitPlugins: Обновлены устаревшие ссылки на диск

---

.github/workflows/publish.RevitLintelPlacement.yml

Добавлен publish файл yml для плагина RevitLintelPlacement

Добавлен publish файл yml для плагина RevitLintelPlacement

---

src/RevitPylonDocumentation/Models/ColorHelper.cs
src/RevitPylonDocumentation/Models/PluginConfig.cs
src/RevitPylonDocumentation/Models/PylonSheetNView/PylonSheetInfo.cs
src/RevitPylonDocumentation/Models/PylonSheetNView/PylonSheetInfoManager.cs
src/RevitPylonDocumentation/Models/PylonSheetNView/PylonView.cs
src/RevitPylonDocumentation/Models/PylonSheetNView/PylonViewLegendPlacer.cs
src/RevitPylonDocumentation/Models/PylonSheetNView/PylonViewScheduleCreator.cs
src/RevitPylonDocumentation/Models/PylonSheetNView/PylonViewSchedulePlacer.cs
src/RevitPylonDocumentation/Models/PylonSheetNView/PylonViewSectionCreator.cs
src/RevitPylonDocumentation/Models/PylonSheetNView/PylonViewSectionPlacer.cs
src/RevitPylonDocumentation/Models/RevitRepository.cs
src/RevitPylonDocumentation/Models/ScheduleFilterParamHelper.cs
src/RevitPylonDocumentation/Models/UnitUtilsHelper.cs
src/RevitPylonDocumentation/Models/UserSettings/UserProjectSettings.cs
src/RevitPylonDocumentation/Models/UserSettings/UserSchedulesSettings.cs
src/RevitPylonDocumentation/Models/UserSettings/UserSelectionSettings.cs
src/RevitPylonDocumentation/Models/UserSettings/UserViewSectionSettings.cs
src/RevitPylonDocumentation/RevitPylonDocumentationCommand.cs
src/RevitPylonDocumentation/ViewModels/MainViewModel.cs
src/RevitPylonDocumentation/Views/MainWindow.xaml
src/RevitPylonDocumentation/Views/MainWindow.xaml.cs
src/RevitPylonDocumentation/Views/TooltipsDictionary.xaml

Подчистил ссылки на лишние библиотеки, отккоректировал нэйминг переменных, внедрил изменения в дефолтные значения настроек плагина (по технологии КР)

RevitPylonDocumentation: Проведен рефакторинг

---

src/RevitMechanicalSpecification/Models/RevitRepository.cs
src/RevitMechanicalSpecification/Service/CollectionFactory.cs
src/RevitMechanicalSpecification/Service/DataOperator.cs
src/RevitMechanicalSpecification/Service/ElementProcessor.cs

Багфикс: IsExistsParam нельзя вызывать в цикле, он его замедляет
Багфикс: Элементы изоляции не попадали в выборку "Выбранные элементы", вместе с их хостами

Полное обновление: правка ошибок

---

src/RevitValueModifier/Models/RevitElement.cs

1. Изменено получение значения параметра в случае, когда значение параметра - пустая строка;
2. Изменено получение параметров типа

RevitValueModifier: скорректировано получение параметров и значений

---

src/RevitLintelPlacement/Models/RevitRepository.cs

Обновление библиотек плагина RevitLintelPlacement

RevitLintelPlacement: Обновление библиотек плагина

---

src/RevitMechanicalSpecification/Service/VisElementsCalculator.cs

Еще одна правка логики, все еще есть жалобы на срабатывание.

RevitMechanicalSpecification: Правка имен фитингов труб

---

src/RevitOpeningPlacement/Models/Configs/OpeningConfig.cs

Т.к. конфиг для настроек расстановки заданий на отверстия от ВИС один на все проекты, то может сложиться ситуация, когда в 1 файле пользователь настроил его, используя параметры этого файла, перешёл в другой файл, в котором какого-то параметра нет, и плагин упал на этапе чтения конфига.
Сделана генерация конфига по умолчанию в случае ошибки десериализации.

RevitOpeningPlacement: При ошибке чтения существующего конфига добавлено создание нового по умолчанию

---

src/RevitMirroredElements/ViewModels/MainViewModel.cs
src/RevitMirroredElements/Views/MainWindow.xaml

- Изменен размер главного окна 
- Исправлена ошибка при первом запуске плагина
- Добавлена возможность изменить размер окна

RevitMirroredElements: Исправлена ошибка при первом запуске плагина и добавлена возможность изменение размера окна 

---

src/RevitReinforcementCoefficient/Models/Analyzers/DesignTypeListAnalyzer.cs
src/RevitReinforcementCoefficient/Models/RevitRepository.cs
src/RevitReinforcementCoefficient/ViewModels/DesignTypeListVM.cs
src/RevitReinforcementCoefficient/ViewModels/DesignTypeVM.cs
src/RevitReinforcementCoefficient/ViewModels/MainViewModel.cs
src/RevitReinforcementCoefficient/Views/MainWindow.xaml

- добавлена возможность фильтровать перечень типов конструкций по секции (DesignTypeListAnalyzer.cs);
- в интерфейсе добавлен ComboBox с возможностью выбора одного из вариантов секции;
- в VM реализовано получение и хранение списка секций и выбора пользователей;
- класс типа конструкции изменен - добавлено поле для значения секции (DesignTypeVM.cs).

RevitReinforcementCoefficient: Добавлена фильтрация по секции

---

src/RevitRoomExtrusion/Models/RoomChecker.cs
src/RevitRoomExtrusion/ViewModels/RoomErrorViewModel.cs

- расширен способ получения помещений, у которых есть самопересечение границ

RevitRoomExtrusion: Обновлен способ получения ошибочных помещений

---

src/RevitRoomExtrusion/Models/FamilyCreator.cs
src/RevitRoomExtrusion/Models/FamilyLoader.cs
src/RevitRoomExtrusion/Models/RevitRepository.cs
src/RevitRoomExtrusion/Models/RoomElement.cs

Внесены изменения подсчёта точки вставки семейства относительно базовой точки проекта

ReviRoomExtrusion :  Изменения подсчёта точки вставки семейства

---

src/RevitRooms/Models/CheckProjectParams.cs

Для автоматической загрузки при запуске скрипта добавлены две новые спецификации ("КВГ_Летние помещения" и "КВГ_(Проверка) Фиксированные площади").

RevitRooms: Добавлены новые спецификации

---

RevitPlugins.sln
src/Directory.Build.targets
src/RevitPlugins/RevitPlugins.csproj
src/RevitPlugins/RevitPluginsCommand.cs
src/RevitPlugins/Views/MainWindow.xaml
src/RevitPlugins/Views/MainWindow.xaml.cs
src/_ProjectProps/WpfUI.props
src/dosymep/WpfUIPlatformWindow.cs

- добавил поддержку wpf-ui
- обновил шаблон RevitPlugins

Добавлена поддержка WPF-UI

---

src/RevitOpeningPlacement/Models/OpeningPlacement/ValueGetters/RoundValueGetter.cs
src/RevitOpeningPlacement/Models/RealOpeningArPlacement/PointFinders/BoundingBoxBottomPointFinder.cs
src/RevitOpeningPlacement/Models/RealOpeningArPlacement/PointFinders/SingleOpeningTaskPointFinder.cs
src/RevitOpeningPlacement/Models/RealOpeningKrPlacement/PointFinders/SingleOpeningArTaskPointFinder.cs

Округление Z координаты точки вставки чистовых отверстий в 10 мм при их автоматическом размещении по заданиям на отверситя заменено на округление в 1 мм.

RevitOpeningPlacement: Скорректировано округление Z координаты точки вставки отверстий АР и КР

---

src/RevitScheduleImport/Localization/Language.en-US.xaml
src/RevitScheduleImport/Localization/Language.ru-RU.xaml
src/RevitScheduleImport/RevitScheduleImport.csproj
src/RevitScheduleImport/RevitScheduleImportCommand.cs
src/RevitScheduleImport/Views/MainWindow.xaml
src/RevitScheduleImport/Views/MainWindow.xaml.cs

В плагин добавлена поддержка WPF-UI.
<div style="align-items: left;">
</div>

RevitScheduleImport: Добавлена поддержка WPF-UI

---

.nuke/parameters.RevitMarkingElements.json

Обновлено:
- Название на 'Маркировка по линии'.
- Расположение кнопки 'Маркировка по линии'

RevitMarkingElements: Изменения расположения и имени

---

src/_ProjectProps/WpfUI.props
src/dosymep/WpfUIPlatformPage.cs
src/dosymep/WpfUIPlatformUserControl.cs
src/dosymep/WpfUIPlatformWindow.cs

- обновил базовые классы под новую версию фреймворка

WPF-UI: Обновлены базовые классы

---

src/RevitClashDetective/ViewModels/ClashDetective/MainViewModel.cs
src/RevitClashDetective/Views/MainWindow.xaml

В окне создания проверок сделана автосортировка по названию проверок

RevitClashDetective: Добавлена автосортировка по названию проверки

---

src/RevitListOfSchedules/Converters/StatusToImageConverter.cs
src/RevitListOfSchedules/Localization/Language.en-US.xaml
src/RevitListOfSchedules/Localization/Language.ru-RU.xaml
src/RevitListOfSchedules/ViewModels/GroupParameterViewModel.cs
src/RevitListOfSchedules/ViewModels/LinkViewModel.cs
src/RevitListOfSchedules/ViewModels/MainViewModel.cs
src/RevitListOfSchedules/Views/MainWindow.xaml

Исправлены ошибки отображение иконок связей, обновления связей, и метода загрузки окна, , установки параметра по дефолту.

RevitListOfSchedules : Исправление ошибок работы плагина

---

src/RevitDeclarations/Models/RoomContours/RoomContour.cs

В алгоритме по объединению и проверке контуров помещений исправлена ошибка.

RevitDeclarations: Исправлена ошибка алгоритма проверки контуров

---

src/RevitMechanicalSpecification/Service/ParamChecker.cs

Для настройки групп параметров, которые могли быть переключены, добавлен новый метод с платформы

RevitMechanicalSpecification: Добавление ReInsertToGroup

---

.nuke/build.schema.json
src/RevitReinforcementCoefficient/Models/Analyzers/DesignTypeAnalyzer.cs
src/RevitReinforcementCoefficient/Models/Analyzers/DesignTypeListAnalyzer.cs
src/RevitReinforcementCoefficient/Models/ElementModels/ElementFactory.cs
src/RevitReinforcementCoefficient/Models/ElementModels/FormworkElement.cs
src/RevitReinforcementCoefficient/Models/ElementModels/ICommonElement.cs
src/RevitReinforcementCoefficient/Models/ElementModels/RebarElement.cs
src/RevitReinforcementCoefficient/Models/ParamUtils.cs
src/RevitReinforcementCoefficient/Models/PluginConfig.cs
src/RevitReinforcementCoefficient/Models/Report/IReportService.cs
src/RevitReinforcementCoefficient/Models/Report/ReportItem.cs
src/RevitReinforcementCoefficient/Models/Report/ReportService.cs
src/RevitReinforcementCoefficient/Models/RevitRepository.cs
src/RevitReinforcementCoefficient/Models/UnitUtilsHelper.cs
src/RevitReinforcementCoefficient/RevitReinforcementCoefficient.csproj
src/RevitReinforcementCoefficient/RevitReinforcementCoefficientCommand.cs
src/RevitReinforcementCoefficient/ViewModels/DesignTypeListVM.cs
src/RevitReinforcementCoefficient/ViewModels/DesignTypeVM.cs
src/RevitReinforcementCoefficient/ViewModels/MainViewModel.cs
src/RevitReinforcementCoefficient/ViewModels/ReportViewModel.cs
src/RevitReinforcementCoefficient/Views/MainWindow.xaml.cs
src/RevitReinforcementCoefficient/Views/ReportWindow.xaml.cs

Произведено обновление кода на C#12

RevitReinforcementCoefficient: Обновление кода на C#12

---

.nuke/build.schema.json
src/RevitFamilyParameterAdder/Models/DefaultParam.cs
src/RevitFamilyParameterAdder/Models/ParameterGroupHelper.cs
src/RevitFamilyParameterAdder/Models/PluginConfig.cs
src/RevitFamilyParameterAdder/Models/RevitRepository.cs
src/RevitFamilyParameterAdder/Models/SharedParam.cs
src/RevitFamilyParameterAdder/RevitFamilyParameterAdder.csproj
src/RevitFamilyParameterAdder/RevitFamilyParameterAdderCommand.cs
src/RevitFamilyParameterAdder/ViewModels/MainViewModel.cs
src/RevitFamilyParameterAdder/Views/MainWindow.xaml.cs

RevitFamilyParameterAdder: Обновление кода на C#12

---

.nuke/build.schema.json
src/RevitOverridingGraphicsInViews/Models/ColorHelper.cs
src/RevitOverridingGraphicsInViews/Models/PluginConfig.cs
src/RevitOverridingGraphicsInViews/Models/RevitRepository.cs
src/RevitOverridingGraphicsInViews/RevitOverridingGraphicsInViews.csproj
src/RevitOverridingGraphicsInViews/RevitOverridingGraphicsInViewsCommand.cs
src/RevitOverridingGraphicsInViews/ViewModels/MainViewModel.cs
src/RevitOverridingGraphicsInViews/Views/MainWindow.xaml
src/RevitOverridingGraphicsInViews/Views/MainWindow.xaml.cs

Произведено обновление кода на C#12

RevitOverridingGraphicsInViews: Обновление кода на C#12

---

src/RevitDeclarations/Models/RoomContours/RoomContour.cs

В случае если в контуре помещения была арка, при проверке контуров могла возникнуть ошибка, приводящая к бесконечному обходу цикла.
Алгоритм проверки контуров теперь изменен. Вместо арок создаются две прямых линии - от начала арки до середины и от середины до конца.

RevitDeclarations: Исправлена ошибка проверки контуров

---

src/RevitRsnManager/Interfaces/IRsnConfigService.cs
src/RevitRsnManager/Models/PluginConfig.cs
src/RevitRsnManager/Models/RevitRepository.cs
src/RevitRsnManager/Models/RsnConfigService.cs
src/RevitRsnManager/Models/Utils/IniConfigurationService.cs
src/RevitRsnManager/RevitRsnEditCommand.cs
src/RevitRsnManager/RevitRsnLoadCommand.cs
src/RevitRsnManager/ViewModels/MainViewModel.cs
src/RevitRsnManager/Views/MainWindow.xaml
src/RevitRsnManager/Views/MainWindow.xaml.cs
src/RevitRsnManager/assets/localization/Language.en-US.xaml
src/RevitRsnManager/assets/localization/Language.ru-RU.xaml

Внесены следующее изменения:
- Исправлена ошибка: При добавлении нового сервера не очищалось вводимое название 
- Исправлена ошибка: Не помещалось сообщение об ошибке
- Исправлено форматирование кода 
- Исправлен интерфейс в соответствии с новыми требованиями

RevitRsnManager: Изменения UI, Исправления Ошибок, Исправлено Форматирование

---

src/RevitRsnManager/RevitRsnLoadCommand.cs

RevitRsnManager: Исправлен путь к локализации

---

src/RevitHideWorkset/Behaviors/SelectedItemsBehavior.cs
src/RevitHideWorkset/Models/LinkedFileElement.cs
src/RevitHideWorkset/Models/RevitRepository.cs
src/RevitHideWorkset/RevitHideWorksetCommand.cs
src/RevitHideWorkset/ViewModels/MainViewModel.cs
src/RevitHideWorkset/Views/MainWindow.xaml
src/RevitHideWorkset/assets/localization/Language.en-US.xaml
src/RevitHideWorkset/assets/localization/Language.ru-RU.xaml

Доработка плагина, реализация следующего функционала:
- Исправлена ошибка: Некорректно работало пакетное скрытие РН из разных файлов
- Добавлена кнопка для пакетного отображения РН рядом с кнопкой "Скрыть"

RevitHideWorkset: Добавлена кнопка "Показать"

---

src/RevitBatchPrint/ViewModels/MainViewModel.cs
src/RevitBatchPrint/ViewModels/SheetViewModel.cs
src/RevitBatchPrint/Views/SheetsView.xaml
src/RevitBatchPrint/ViewsTemplates/TreeViewTemplate.xaml

- добавил отображение номера листа
- добавил сортировку по номеру листа
- некоторые улучшения в отображении списка листов

RevitBatchPrint: Добавлено отображение номера листа

---

src/RevitCorrectNamingCheck/Helpers/NamingRulesHelper.cs
src/RevitCorrectNamingCheck/Models/LinkedFile.cs
src/RevitCorrectNamingCheck/Models/LinkedFileEnricher.cs
src/RevitCorrectNamingCheck/Models/NameStatus.cs
src/RevitCorrectNamingCheck/Models/PluginConfig.cs
src/RevitCorrectNamingCheck/Models/RevitRepository.cs
src/RevitCorrectNamingCheck/Models/WorksetInfo.cs
src/RevitCorrectNamingCheck/RevitCorrectNamingCheckCommand.cs
src/RevitCorrectNamingCheck/ViewModels/MainViewModel.cs
src/RevitCorrectNamingCheck/Views/Selectors/WorksetTemplateSelector.cs

RevitCorrectNamingCheck: CleanUp проекта

---

src/RevitClashDetective/ViewModels/Navigator/ClashViewModel.cs
src/RevitClashDetective/ViewModels/Navigator/ReportViewModel.cs
src/RevitClashDetective/Views/NavigatorView.xaml
src/RevitClashes/Models/GraphicView/ParameterFilterProvider.cs

- Добавлен общий % пересечения по каждой выборке элементов
- Исправлена генерация фильтра для выбора элементов с отрицательными значениями параметров

RevitClashDetective: Добавлен общий % пересечения

---

src/RevitBatchPrint/Models/RevitRepository.cs
src/RevitBatchPrint/Views/MainWindow.xaml
src/RevitBatchPrint/assets/localization/Language.en-US.xaml
src/RevitBatchPrint/assets/localization/Language.ru-RU.xaml

- добавил поддержку пользовательских параметров "Ширина" и "Высота", на данный момент имена параметров берутся из ресурсов локализации.

RevitBatchPrint: Улучшение определения "Ширины" и "Высоты" листа

---

src/RevitSectionsConstructor/Models/ActionsOnGroup.cs
src/RevitSectionsConstructor/Models/GroupWithAction.cs
src/RevitSectionsConstructor/Models/LevelWrapper.cs
src/RevitSectionsConstructor/Models/RevitRepository.cs
src/RevitSectionsConstructor/RevitSectionsConstructor.csproj
src/RevitSectionsConstructor/RevitSectionsConstructorCommand.cs
src/RevitSectionsConstructor/Services/DocumentSaver.cs
src/RevitSectionsConstructor/Services/GroupsHandler.cs
src/RevitSectionsConstructor/ViewModels/GroupViewModel.cs
src/RevitSectionsConstructor/ViewModels/MainViewModel.cs
src/RevitSectionsConstructor/Views/MainWindow.xaml
src/RevitSectionsConstructor/Views/MainWindow.xaml.cs

Конструктор секций: Код плагина обновлен на C#12

---

.github/workflows/publish.RevitSectionsConstructor.yml
src/RevitSectionsConstructor/Models/RevitRepository.cs
src/RevitSectionsConstructor/RevitSectionsConstructor.csproj
src/RevitSectionsConstructor/RevitSectionsConstructorCommand.cs
src/RevitSectionsConstructor/Services/DocumentSaver.cs
src/RevitSectionsConstructor/Services/GroupsHandler.cs
src/RevitSectionsConstructor/ViewModels/MainViewModel.cs
src/RevitSectionsConstructor/Views/MainWindow.xaml
src/RevitSectionsConstructor/Views/MainWindow.xaml.cs
src/RevitSectionsConstructor/assets/Localization/Language.en-US.xaml
src/RevitSectionsConstructor/assets/Localization/Language.ru-RU.xaml

- Добавлена локализация
- devexpress заменен на WPF-UI

RevitSectionsConstructor: Плагин портирован на WPF-UI

---

src/RevitClashDetective/ViewModels/Navigator/ClashViewModel.cs
src/RevitClashDetective/ViewModels/Navigator/ElementViewModel.cs
src/RevitClashDetective/ViewModels/Navigator/ReportViewModel.cs

- Исправлены единицы измерения объема в расчетах

RevitClashDetective: Исправлены единицы измерения в расчете

---

src/RevitAxonometryViews/Models/AxonometryConfig.cs
src/RevitAxonometryViews/Models/CollectorOperator.cs
src/RevitAxonometryViews/Models/CreationViewRules.cs
src/RevitAxonometryViews/Models/RevitRepository.cs
src/RevitAxonometryViews/Models/ViewFactory.cs
src/RevitAxonometryViews/RevitAxonometryViews.csproj
src/RevitAxonometryViews/RevitAxonometryViewsCommand.cs
src/RevitAxonometryViews/ViewModels/HvacSystemViewModel.cs
src/RevitAxonometryViews/ViewModels/MainViewModel.cs
src/RevitAxonometryViews/Views/MainWindow.xaml.cs

RevitAxonometryViews: Обновление кода на C#12

---

src/RevitCreateViewSheet/Views/MainWindow.xaml

- Упрощен столбец со статусом листа и исправлена сортировка по нему.

RevitCreateViewSheet: Исправлена сортировка столбца со статусом листа

---

src/RevitServerFolders/Models/ExportSettings.cs
src/RevitServerFolders/Services/NwcExportService.cs
src/RevitServerFolders/ViewModels/ExportSettingsViewModel.cs
src/RevitServerFolders/ViewModels/MainViewModel.cs
src/RevitServerFolders/Views/MainWindow.xaml
src/RevitServerFolders/Views/SettingsView.xaml
src/RevitServerFolders/Views/SettingsView.xaml.cs
src/RevitServerFolders/assets/Localization/Language.en-US.xaml
src/RevitServerFolders/assets/Localization/Language.ru-RU.xaml

- Исправлен сброс выбранных файлов из папки источника при переключении между пресетами
- Настройки пресета вынесены в отдельный UserControl
- Добавлено сохранение выбранных пресетов
- Выключена валидация выключенных пресетов
- Добавляемый пресет теперь по умолчанию включен
- При старте окна теперь выбирается первый включенный пресет с прошлого запуска, или первый сгенерированный пресет, если плагин запускается впервые

RevitServerFolders: Исправлен сброс выбранных файлов при переключении между пресетами

---

src/RevitServerFolders/ViewModels/ExportSettingsViewModel.cs
src/RevitServerFolders/ViewModels/FileModelObjectExportSettingsViewModel.cs
src/RevitServerFolders/ViewModels/RsModelObjectExportSettingsViewModel.cs
src/RevitServerFolders/Views/MainWindow.xaml
src/RevitServerFolders/Views/SettingsView.xaml

- Добавлена кнопка для выгрузки RVT из RS для обновления моделей из папки источника

RevitServerFolders: В RVT из RS добавлена кнопка для обновления списка с моделями из папки источника 
